# Generated by Django 6.0.7 on 2026-07-25 16:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('event_approuve', 'Événement approuvé'), ('event_refuse', 'Événement refusé'), ('event_revision', 'Révision demandée'), ('event_publie', 'Événement publié'), ('event_modifie', 'Événement modifié'), ('event_annule', 'Événement annulé'), ('inscription_confirmee', 'Inscription confirmée'), ('paiement_confirme', 'Paiement confirmé'), ('billet_disponible', 'Billet disponible')], max_length=30, verbose_name='Type')),
                ('titre', models.CharField(max_length=150, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('lien', models.CharField(blank=True, max_length=255, verbose_name='Lien')),
                ('lu', models.BooleanField(db_index=True, default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['destinataire', 'lu'], name='notificatio_destina_353850_idx')],
            },
        ),
    ]
