# Generated by Django 6.0.7 on 2026-07-25 14:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('campay', 'CamPay'), ('stripe', 'Stripe'), ('cinetpay', 'CinetPay'), ('flutterwave', 'Flutterwave')], default='campay', max_length=20, verbose_name='Fournisseur')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('devise', models.CharField(default='XAF', max_length=3, verbose_name='Devise')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone Mobile Money')),
                ('reference_externe', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Référence externe')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], db_index=True, default='en_attente', max_length=15, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='inscriptions.inscription')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evenement', models.CharField(max_length=50, verbose_name='Événement')),
                ('payload_brut', models.JSONField(default=dict, verbose_name='Payload brut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Transaction de paiement',
                'verbose_name_plural': 'Transactions de paiement',
                'ordering': ['-created_at'],
            },
        ),
    ]
