# Generated by Django 6.0.7 on 2026-07-24 17:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizers', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(db_index=True, max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('categorie', models.CharField(choices=[('conference', 'Conférence'), ('atelier', 'Atelier'), ('culturel', 'Culturel'), ('sportif', 'Sportif'), ('academique', 'Académique'), ('autre', 'Autre')], db_index=True, default='autre', max_length=20, verbose_name='Catégorie')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/images/%Y/%m/', verbose_name='Image')),
                ('lieu', models.CharField(db_index=True, max_length=255, verbose_name='Lieu')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('date_debut', models.DateTimeField(db_index=True, verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(db_index=True, verbose_name='Date de fin')),
                ('capacite_max', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacité maximale')),
                ('places_restantes', models.PositiveIntegerField(verbose_name='Places restantes')),
                ('type_paiement', models.CharField(choices=[('gratuit', 'Gratuit'), ('payant', 'Payant')], default='gratuit', max_length=10, verbose_name='Type de paiement')),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix')),
                ('devise', models.CharField(default='XAF', max_length=3, verbose_name='Devise')),
                ('statut', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de validation'), ('revision_requested', 'Révision demandée'), ('published', 'Publié'), ('rejected', 'Refusé'), ('cancelled', 'Annulé'), ('finished', 'Terminé'), ('archived', 'Archivé')], db_index=True, default='draft', max_length=25, verbose_name='Statut')),
                ('motif_refus', models.TextField(blank=True, verbose_name='Motif de refus')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publié le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='organizers.organizer', verbose_name='Organisateur')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='EventReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='events.event', verbose_name='Événement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_evenements', to='students.student', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Avis événement',
                'verbose_name_plural': 'Avis événements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, choices=[('draft', 'Brouillon'), ('pending', 'En attente de validation'), ('revision_requested', 'Révision demandée'), ('published', 'Publié'), ('rejected', 'Refusé'), ('cancelled', 'Annulé'), ('finished', 'Terminé'), ('archived', 'Archivé')], max_length=25, verbose_name='Ancien statut')),
                ('nouveau_statut', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de validation'), ('revision_requested', 'Révision demandée'), ('published', 'Publié'), ('rejected', 'Refusé'), ('cancelled', 'Annulé'), ('finished', 'Terminé'), ('archived', 'Archivé')], max_length=25, verbose_name='Nouveau statut')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_statuts', to='events.event', verbose_name='Événement')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique de statut',
                'verbose_name_plural': 'Historiques de statuts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['statut', 'date_debut'], name='events_even_statut_b8926e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizer', 'statut'], name='events_even_organiz_9224ed_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['categorie', 'statut'], name='events_even_categor_50b353_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['titre'], name='events_even_titre_7842fa_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['lieu'], name='events_even_lieu_b1bdef_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('date_fin__gt', models.F('date_debut'))), name='event_date_fin_apres_date_debut'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('places_restantes__lte', models.F('capacite_max'))), name='event_places_restantes_inferieur_capacite'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('capacite_max__gte', 1)), name='event_capacite_max_positive'),
        ),
        migrations.AddConstraint(
            model_name='eventreview',
            constraint=models.UniqueConstraint(fields=('event', 'student'), name='event_review_unique_par_etudiant'),
        ),
        migrations.AddIndex(
            model_name='eventstatushistory',
            index=models.Index(fields=['event', 'created_at'], name='events_even_event_i_fd0965_idx'),
        ),
    ]
