# Generated by Django 6.0.7 on 2026-07-22 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=255, verbose_name='Club / Association')),
                ('departement', models.CharField(blank=True, max_length=150, verbose_name='Département')),
                ('poste', models.CharField(choices=[('president', 'Président'), ('vice_president', 'Vice-président'), ('secretaire', 'Secrétaire'), ('tresorier', 'Trésorier'), ('membre', 'Membre')], max_length=20, verbose_name='Poste')),
                ('date_debut_mandat', models.DateField(verbose_name='Date de prise de fonction')),
                ('date_fin_mandat', models.DateField(blank=True, null=True, verbose_name='Date de fin de mandat')),
                ('bureau_local', models.CharField(blank=True, max_length=100, verbose_name='Bureau / Local')),
                ('biographie', models.TextField(blank=True, verbose_name='Biographie')),
                ('signature_electronique', models.ImageField(blank=True, null=True, upload_to='organizers/signatures/%Y/', verbose_name='Signature électronique')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=20, verbose_name='Statut')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil organisateur',
                'verbose_name_plural': 'Profils organisateurs',
                'indexes': [models.Index(fields=['club', 'statut'], name='organizers__club_f13a67_idx')],
            },
        ),
    ]
