# Generated by Django 6.0.7 on 2026-07-24 10:52

import gather.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fuseau_horaire',
            field=models.CharField(choices=gather.users.models.get_timezone_choices, default='Africa/Douala', max_length=50, verbose_name='Fuseau horaire'),
        ),
    ]
