# Generated by Django 6.0.7 on 2026-07-25 11:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('confirmee', 'Confirmée'), ('annulee', 'Annulée')], db_index=True, default='confirmee', max_length=15, verbose_name='Statut')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name='Inscrit le')),
                ('date_annulation', models.DateTimeField(blank=True, null=True, verbose_name='Annulé le')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='events.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='students.student')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_qr', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Code QR')),
                ('image_qr', models.ImageField(blank=True, null=True, upload_to='tickets/qrcodes/%Y/%m/', verbose_name='Image QR')),
                ('statut', models.CharField(choices=[('valide', 'Valide'), ('utilise', 'Utilisé'), ('annule', 'Annulé')], db_index=True, default='valide', max_length=15, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_utilisation', models.DateTimeField(blank=True, null=True, verbose_name='Utilisé le')),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='inscriptions.inscription')),
            ],
            options={
                'verbose_name': 'Billet',
                'verbose_name_plural': 'Billets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['event', 'statut'], name='inscription_event_i_257568_idx'),
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['student', 'statut'], name='inscription_student_7033c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'confirmee')), fields=('event', 'student'), name='inscription_active_unique_par_etudiant_et_evenement'),
        ),
    ]
