# Generated by Django 6.0.7 on 2026-07-26 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0001_initial'),
    ]

    operations = [
    ]
