# Generated by Django 6.0.7 on 2026-07-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('inscriptions', '0002_schedule_rappels_24h'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='statut',
            field=models.CharField(choices=[('en_attente_paiement', 'En attente de paiement'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée')], db_index=True, default='confirmee', max_length=25, verbose_name='Statut'),
        ),
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'en_attente_paiement')), fields=('event', 'student'), name='inscription_attente_unique_par_etudiant_et_evenement'),
        ),
    ]
