# Generated by Django 6.0.7 on 2026-07-22 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Matricule')),
                ('filiere', models.CharField(max_length=150, verbose_name='Filière')),
                ('departement', models.CharField(db_index=True, max_length=150, verbose_name='Département')),
                ('niveau_etude', models.CharField(max_length=20, verbose_name="Niveau d'étude")),
                ('promotion', models.CharField(help_text='Ex: 2025-2026', max_length=9, verbose_name='Promotion')),
                ('groupe', models.CharField(blank=True, max_length=50, verbose_name='Groupe / Classe')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('statut_academique', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('diplome', 'Diplômé'), ('abandon', 'Abandon')], db_index=True, default='actif', max_length=20, verbose_name='Statut académique')),
                ('photo_carte_etudiante', models.ImageField(blank=True, null=True, upload_to='students/cartes/%Y/', verbose_name='Photo carte étudiante')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil étudiant',
                'verbose_name_plural': 'Profils étudiants',
                'indexes': [models.Index(fields=['departement', 'promotion'], name='students_st_departe_a3b7a9_idx')],
            },
        ),
    ]
